# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9611ae4b739ceba4414f8b470d0cb3d23b3d598bf7d062490bb23115ce99bd78d69e9d6f7fc0f9915e7fef0da723b0ca479c3bfe1c4011fec9fc35ebb6ca695e

test:
  secret_key_base: b1b8a7b04466ec39cfcc1e554cf3bfc0fc649dd15a4594086850efdbebd93e2832a966c8ac8c06a1c05643bb13eac4d8dcb59be673f4437785777c9a7cd00e08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
