# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d64949df3bbe38e6b0811cb169e9aaeddf873ffadcc28ea9b0d113bfa8e00d927552123fb61d8f0b0d7bbec3e1c0a36d174968e1d4ca0eed41382720ec018edc

test:
  secret_key_base: 7287627da7fcc75213d941aece0ab7e4b282617389e3700ba602de938273957735d345f4d13e9041ec3e6d408593b040b7bf33dea027157cc1add597e53212d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
